CREATE SEQUENCE FLYERID START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999;

CREATE SEQUENCE INSKEY START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999;

CREATE SEQUENCE PKEY START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999;

CREATE SEQUENCE CKEY START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999;

CREATE SEQUENCE PDET START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999;

CREATE SEQUENCE PNR START WITH 10
INCREMENT BY 1
MINVALUE 10
MAXVALUE 1000000000;