CREATE OR REPLACE FUNCTION GET_BOOKING_DETAILS (NAME_READ IN VARCHAR2)
RETURN VARCHAR2
AS
	PID NUMBER (3);
	CURSOR LCSR IS SELECT PNR FROM BOOKING_DETAILS WHERE FLYER_ID = PID;
	LREC LCSR%rowtype;
	RVAL VARCHAR2 (500) := ' ';
BEGIN
	SELECT FLYER_ID INTO PID FROM PASSENGER_DETAILS WHERE NAME = NAME_READ;
	OPEN LCSR;
	LOOP
		FETCH LCSR INTO LREC;
		EXIT WHEN LCSR%NOTFOUND;
		RVAL := RVAL || 'PNR: ' || LREC.PNR || ', ';
	END LOOP;
	RETURN RVAL;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
	RETURN 'ERROR: NAME CANNOT BE MAPPED TO ONE PASSENGER.';
WHEN NO_DATA_FOUND THEN
	RETURN 'ERROR: NO SUCH PASSENGER EXISTS IN DATABASE.';
WHEN OTHERS THEN
	RETURN 'ERROR OCCURED. CODE UDF_PL100. PLEASE CONTACT ADMINISTRATOR.';
END;

CREATE OR REPLACE FUNCTION GET_ALL_BOOKING_DETAILS(PNR_READ IN NUMBER)
RETURN VARCHAR2
AS
	RVAL VARCHAR2 (1500) := ' ';
	R_NAME VARCHAR2 (50);
	R_FLIGHT_NO VARCHAR2 (6);
	R_DATE_OF_JOURNEY DATE;
	R_AMOUNT NUMBER (10);
BEGIN
	SELECT NAME, FLIGHT_NO, DATE_OF_JOURNEY, AMOUNT
	INTO R_NAME, R_FLIGHT_NO, R_DATE_OF_JOURNEY, R_AMOUNT
	FROM BOOKING_DETAILS, CLASSKEY, PAYKEY, PAYMENT_DETAILS, PASSENGER_DETAILS
	WHERE PNR = PNR_READ
	AND BOOKING_DETAILS.FLYER_ID = PASSENGER_DETAILS.FLYER_ID
	AND PAYMENT_DETAILS.PAYMENT_ID = BOOKING_DETAILS.PAYMENT_ID
	AND PAYMENT_DETAILS.PAYMENT_MODE = PAYKEY.PAYMENT_MODE
	AND CLASSKEY.CLASS = BOOKING_DETAILS.CLASS;
	RVAL := 'QUERY FOR PNR: ' || PNR_READ ||
	' |||  PASSENGER NAME: ' || R_NAME ||
	' |||  FLIGHT NUMBER: ' || R_FLIGHT_NO ||
	' |||  DATE OF JOURNEY: ' || R_DATE_OF_JOURNEY ||
	' |||  AMOUNT: ' || R_AMOUNT;
	RETURN RVAL;
EXCEPTION
WHEN TOO_MANY_ROWS THEN
	RETURN 'DATABASE DISCREPANCY: TOO MANY ROWS FOUND. ERROR CODE UDF_PL101. PLEASE CONTACT ADMINISTRATOR.';
WHEN NO_DATA_FOUND THEN
	RETURN 'GIVEN PNR CANNOT BE MAPPED TO ANY BOOKING. PLEASE CHECK PNR. TO GET PNR FROM PASSENGER NAME, USE GET_BOOKING_DETAILS';
WHEN OTHERS THEN
	RETURN 'ERROR OCCURED. CODE UDF_PL102. PLEASE CONTACT ADMINISTRATOR.';
END;