SELECT * FROM AIRPORTS;
SELECT * FROM BOOKING_DETAILS;
SELECT * FROM CLASSKEY;
SELECT * FROM COMPANY_DETAILS;
SELECT * FROM FLIGHT_OPERATORS;
SELECT * FROM PASSENGER_DETAILS;
SELECT * FROM PAYKEY;
SELECT * FROM PAYMENT_DETAILS;