SET VERIFY OFF;
SET SERVEROUTPUT ON;

DECLARE
	FID NUMBER (3) := &ENTER_FLYER_ID;
	FNO VARCHAR2 (6) := '&ENTER_FLIGHT_NUMBER';
	CLAS NUMBER (3) := &ENTER_CLASS;
	FTP VARCHAR2 (5) := '&ENTER_FOOD_TYPE';
	DOJ DATE := '&DATE_OF_JOURNEY';
	LCD VARCHAR2 (3) := '&ENTER_LUXURY_CODE';
	PMD NUMBER (3) := &ENTER_PAYMENT_MODE;
	AMT NUMBER (10) := &ENTER_AMOUNT_CHARGED;
BEGIN
	ADD_TICKET(FID, FNO, CLAS, FTP, DOJ, LCD, PMD, AMT);
END;