DROP TABLE AIRPORTS;
DROP TABLE BOOKING_DETAILS;
DROP TABLE CLASSKEY;
DROP TABLE COMPANY_DETAILS;
DROP TABLE FLIGHT_OPERATORS;
DROP TABLE PASSENGER_DETAILS;
DROP TABLE PAYKEY;
DROP TABLE PAYMENT_DETAILS;