CREATE OR REPLACE PROCEDURE MAKE_CLASS (CNAME IN VARCHAR2)
AS
	CODE NUMBER(3);
BEGIN
	SELECT CKEY.NEXTVAL INTO CODE FROM DUAL;
	INSERT INTO CLASSKEY VALUES (CODE, CNAME);
END;

CREATE OR REPLACE PROCEDURE MAKE_PAYKEY (PNAME IN VARCHAR2)
AS
	CODE NUMBER(3);
BEGIN
	SELECT PKEY.NEXTVAL INTO CODE FROM DUAL;
	INSERT INTO PAYKEY VALUES (CODE, PNAME);
END;

CREATE OR REPLACE PROCEDURE MAKE_PAYMENT (PMODE IN NUMBER, AMT IN NUMBER, CODE OUT NUMBER)
AS
BEGIN
	SELECT PDET.NEXTVAL INTO CODE FROM DUAL;
	INSERT INTO PAYMENT_DETAILS VALUES (CODE, PMODE, AMT);
END;

CREATE OR REPLACE PROCEDURE ADD_USER (NAME IN VARCHAR2, PHNO IN NUMBER, DOB IN DATE, MAIL IN VARCHAR2, PASSWD IN VARCHAR2)
AS
	CODE NUMBER(3);
BEGIN
	SELECT FLYERID.NEXTVAL INTO CODE FROM DUAL;
	INSERT INTO PASSENGER_DETAILS VALUES (CODE, NAME, PHNO, DOB, MAIL, PASSWD);
END;

CREATE OR REPLACE PROCEDURE ADD_TICKET (FLID IN NUMBER, FLNO IN VARCHAR2, CLASS IN NUMBER, FTYPE IN VARCHAR2, DOJ IN DATE, LCODE IN VARCHAR, PMODE IN NUMBER, PAMT IN NUMBER)
AS
	CPNR NUMBER(15);
	DOB DATE;
	PID NUMBER(10);
	SCOUNT NUMBER(4);
	SBOOKED NUMBER(4);
BEGIN
	SELECT COUNT(PNR) INTO SBOOKED FROM BOOKING_DETAILS WHERE FLIGHT_NO = FLNO AND DATE_OF_JOURNEY = DOJ GROUP BY FLIGHT_NO, DATE_OF_JOURNEY;
	SELECT CAPACITY INTO SCOUNT FROM COMPANY_DETAILS, FLIGHT_OPERATORS WHERE FLIGHT_NO = FLNO AND COMPANY_DETAILS.COMPANY_ID = FLIGHT_OPERATORS.COMPANY_ID;
	IF SCOUNT = SBOOKED THEN
		DBMS_OUTPUT.PUT_LINE('ALL SEATS FOR REQUESTED FLIGHT ON REQUESTED DATE ARE BOOKED. SORRY!');
	ELSE
		SELECT PNR.NEXTVAL INTO CPNR FROM DUAL;
		SELECT SYSDATE INTO DOB FROM DUAL;
		MAKE_PAYMENT(PMODE, PAMT, PID);
		INSERT INTO BOOKING_DETAILS VALUES (CPNR, FLID, FLNO, CLASS, FTYPE, DOJ, DOB, LCODE, PID);
	END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('NO RECORDS FOR THIS FLIGHT ON GIVEN DATE. PLEASE CREATE ENTRY USING MAKE_TICKET');
END;

CREATE OR REPLACE PROCEDURE MAKE_TICKET (FLID IN NUMBER, FLNO IN VARCHAR2, CLASS IN NUMBER, FTYPE IN VARCHAR2, DOJ IN DATE, LCODE IN VARCHAR, PMODE IN NUMBER, PAMT IN NUMBER)
AS
	CPNR NUMBER(15);
	DOB DATE;
	PID NUMBER(10);
BEGIN
	SELECT PNR.NEXTVAL INTO CPNR FROM DUAL;
	SELECT SYSDATE INTO DOB FROM DUAL;
	MAKE_PAYMENT(PMODE, PAMT, PID);
	INSERT INTO BOOKING_DETAILS VALUES (CPNR, FLID, FLNO, CLASS, FTYPE, DOJ, DOB, LCODE, PID);
END;