CREATE TABLE PASSENGER_DETAILS(
	FLYER_ID NUMBER (3) PRIMARY KEY,
	NAME VARCHAR2 (50) NOT NULL,
	PHONE_NUMBER NUMBER (11) NOT NULL,
	DOB DATE NOT NULL,
	MAIL_ID VARCHAR2 (100) UNIQUE NOT NULL,
	PASSWORD VARCHAR2 (160) NOT NULL
);

CREATE TABLE PAYKEY(
	PAYMENT_MODE NUMBER (3) PRIMARY KEY,
	MEANING VARCHAR2 (50) NOT NULL
);

CREATE TABLE CLASSKEY(
	CLASS NUMBER (3) PRIMARY KEY,
	MEANING VARCHAR2 (50) NOT NULL
);

CREATE TABLE PAYMENT_DETAILS(
	PAYMENT_ID NUMBER (10) PRIMARY KEY,
	PAYMENT_MODE NUMBER (3) NOT NULL REFERENCES PAYKEY (PAYMENT_MODE),
	AMOUNT NUMBER (20) NOT NULL
);

CREATE TABLE COMPANY_DETAILS(
	COMPANY_ID VARCHAR2 (10) PRIMARY KEY,
	COMPNAY_NAME VARCHAR2 (50) NOT NULL,
	FLIGHT_TYPE VARCHAR2 (10) NOT NULL,
	CAPACITY NUMBER (4) NOT NULL,
	LICENSE_ID VARCHAR2 (20) NOT NULL,
	LICENSE_COST NUMBER (10) NOT NULL,
	LICENSE_VALIDITY NUMBER (5) NOT NULL
);

CREATE TABLE AIRPORTS(
	AIR_CODE VARCHAR2 (5) PRIMARY KEY,
	AIRPORT_NAME VARCHAR2 (50) NOT NULL
);

CREATE TABLE FLIGHT_OPERATORS(
	FLIGHT_NO VARCHAR2 (10) PRIMARY KEY,
	COMPANY_ID VARCHAR2 (10) NOT NULL REFERENCES COMPANY_DETAILS (COMPANY_ID),
	SOURCE VARCHAR2 (5) NOT NULL REFERENCES AIRPORTS (AIR_CODE),
	DESTINATION VARCHAR2 (5) NOT NULL REFERENCES AIRPORTS (AIR_CODE),
	SCHEDULED_TAKEOFF interval day to second NOT NULL,
	SCHEDULED_LANDING interval day to second NOT NULL,
	AVG_TAKEOFF_DELAY interval day to second,
	AVG_LANDING_DELAY interval day to second
);

CREATE TABLE BOOKING_DETAILS(
	PNR NUMBER (15) PRIMARY KEY,
	FLYER_ID NUMBER (3) NOT NULL REFERENCES PASSENGER_DETAILS (FLYER_ID),
	FLIGHT_NO VARCHAR2 (10) NOT NULL REFERENCES FLIGHT_OPERATORS (FLIGHT_NO),
	CLASS NUMBER (3) NOT NULL REFERENCES CLASSKEY (CLASS),
	FOOD_TYPE VARCHAR2 (5),
	DATE_OF_JOURNEY DATE NOT NULL,
	DATE_OF_BOOKING DATE NOT NULL,
	LUX_CODE VARCHAR2 (3),
	PAYMENT_ID NUMBER (10) NOT NULL REFERENCES PAYMENT_DETAILS (PAYMENT_ID)
);